version: "3.9"

#name: anythingllm

networks:
  network:
    external:
      name: appliance

services:
  anything-llm-sqlagent-new:
    container_name: anything-llm-sql-agent-new
    image: anything-llm:new
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3015:3001"
    env_file:
      - .env
    networks:
      - "network"

